[Interface]
PrivateKey = Wn4UZhnLAmXn2KQ8IAQVQepstskX/UgH3HTZExrytyg=
Address = 100.82.33.215/32, fd00::15:2b26/128
DNS = 169.254.169.254, 1.1.1.1, 1.0.0.1
MTU = 1280

[Peer]
PublicKey = 4s1aCCjdlKxSA9DBfZnzOTLw0gVHJsLgUUaSW+4mRSQ=
PresharedKey = QDsptrHaD8srZaO5yi/vmJwZRNYB/bR0P1djk5v38N8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = vpn.danarapay.com:51820
PersistentKeepalive = 25
